<a href="https://colab.research.google.com/github/javeddd12/Simulation-and-Modeling-Lab/blob/main/SIM_Lab1_Javed_Hossain_1043.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

1.**Scalar & Array Operations** (Redo Section with Your Own Values):

Run the given code with scalar = 3.7 and a new array of at least 6 elements.


Show outputs of all built-in mathematical functions (sin, cos, tan, etc.).


In [ ]:
scalar = 3.7
arr = np.array([1, 2, 3, 4, 5, 6])

sin_values = np.sin(arr)
cos_values = np.cos(arr)
tan_values = np.tan(arr)

print("sin:", sin_values)
print("cos:", cos_values)
print("tan:", tan_values)

sin: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
cos: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029]
tan: [ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619]


2.**Task:** Apply the Same Operations on a 3×2 Matrix

Create a 3×2 matrix with custom values.


Perform and display results of:
Trigonometric functions

Exponential & logarithmic functions

Absolute value & square root

Remainder when divided by 2


Rounding (round, floor, ceil)


In [ ]:
# Creating a 3x2 matrix
matrix = np.array([[1, 2.16], [3.4, 4],[5.845757, 6.5678]])

sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)
asin_values = np.arcsin(np.clip(matrix / np.max(matrix), -1, 1))
acos_values = np.arccos(np.clip(matrix / np.max(matrix), -1, 1))
atan_values = np.arctan(matrix)


exp_values = np.exp(matrix)
log_values = np.log(matrix)


abs_values = np.abs(matrix)
sqrt_values = np.sqrt(matrix)


rem_values = np.remainder(matrix, 2)


round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)


print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasine:\n", asin_values)
print("\nacosine:\n", acos_values)
print("\natangent:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog (natural):\n", log_values)
print("\nabs:\n", abs_values)
print("\nsqrt:\n", sqrt_values)
print("\nrem (remainder when divided by 2):\n", rem_values)
print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)

Matrix:
 [[-1.        2.16    ]
 [ 3.4      -4.      ]
 [ 5.845757 -6.5678  ]]

sin:
 [[-0.84147098  0.83138346]
 [-0.2555411   0.7568025 ]
 [-0.42361132 -0.28078767]]

cos:
 [[ 0.54030231 -0.55569915]
 [-0.96679819 -0.65364362]
 [ 0.90584406  0.95976991]]

tan:
 [[-1.55740772 -1.49610354]
 [ 0.2643169  -1.15782128]
 [-0.46764265 -0.29255727]]

asine:
 [[-0.17190973  0.37846956]
 [ 0.62071684 -0.75358431]
 [ 1.57079633 -1.57079633]]

acosine:
 [[1.74270606 1.19232677]
 [0.95007949 2.32438064]
 [0.         3.14159265]]

atangent:
 [[-0.78539816  1.13721484]
 [ 1.28474489 -1.32581766]
 [ 1.401372   -1.41969881]]

exp:
 [[3.67879441e-01 8.67113766e+00]
 [2.99641000e+01 1.83156389e-02]
 [3.45764186e+02 1.40488476e-03]]

log (natural):
 [[       nan 0.77010822]
 [1.22377543        nan]
 [1.7657161         nan]]

abs:
 [[1.       2.16    ]
 [3.4      4.      ]
 [5.845757 6.5678  ]]

sqrt:
 [[       nan 1.46969385]
 [1.84390889        nan]
 [2.41780003        nan]]

rem (remainder when divide

/tmp/ipython-input-685639740.py:13: RuntimeWarning: invalid value encountered in log
  log_values = np.log(matrix)
/tmp/ipython-input-685639740.py:17: RuntimeWarning: invalid value encountered in sqrt
  sqrt_values = np.sqrt(matrix)


3.**Task:** Perform Same Operations on a 2×3 Matrix

Your 2×3 matrix can have float values (e.g., 2.1, 4.7…).


Implement and display:


Max & Min (with indices)


Vector length


Sorted version (both row-wise descending and entire matrix descending)


Sum, Product


Median, Mean, Standard Deviation


In [ ]:
# Sample vector (1D array)
vec = np.array([[1, 2.1, 4 ], [3.4, 4.7, 8]])


max_value = np.max(vec)
max_index = np.argmax(vec)


min_value = np.min(vec)
min_index = np.argmin(vec)

vec_length = len(vec)


sorted_vec = np.sort(vec)



sum_values = np.sum(vec)

prod_values = np.prod(vec)


median_value = np.median(vec)


mean_value = np.mean(vec)

std_dev = np.std(vec)

# Display results
print("Max value:", max_value, "at index", max_index)
print("Min value:", min_value, "at index", min_index)
print("Length of vector:", vec_length)
print("Sorted vector:", sorted_vec)
print("Sum of elements:", sum_values)
print("Product of elements:", prod_values)
print("Median value:", median_value)
print("Mean value:", mean_value)
print("Standard deviation:", std_dev)

Max value: 8.0 at index 5
Min value: 1.0 at index 0
Length of vector: 2
Sorted vector: [[1.  2.1 4. ]
 [3.4 4.7 8. ]]
Sum of elements: 23.2
Product of elements: 1073.856
Median value: 3.7
Mean value: 3.8666666666666667
Standard deviation: 2.2118368434905458
